
:::{.content-hidden when-format="html" when-page="index"}
# Local Development Tools for Python Programming
:::

Install and configure tools to help you manage and develop Python programs like a professional. Attendees will become familiar with development tools such as a text editor and command line application.

## Learning Objectives

1. Utilize local development tools to write and execute Python code for research and software development.
2. Use GitHub Desktop software to download existing Python repositories from GitHub.
3. Use a text editor to read, write, and save files of Python code.
4. Create and manage virtual environments using Anaconda.
5. Manage package installations effectively using Pip within a virtual environment, and practice using a requirements file to list package dependencies for a given project.
6. Run Python programs on your computer.
7. Discuss security measures needed to protect secret credentials used by research and application code.

## Prerequisites

This workshop requires the following software:

+ GitHub Desktop (requires a GitHub account)
+ VS Code Text Editor
+ Anaconda, Python, and Pip
+ Command Line Application (Terminal on Mac, Git Bash on Windows)

If you have never worked with these tools before, we will walk you through how to install them. Just follow the [Local Development Environment Setup Guide](./prereqs/local-dev-setup/index.qmd). We will use a "Full Setup" for the exercises in this workshop.

## Agenda

+ 0:00 - Welcome and Announcements:
  + Make sure you have already installed the prerequisite software before the workshop. It may take a few hours, so get started early, like a few days in advance.
+ 0:05 - Installation Support:
  + If anyone ran into issues installing the prerequisite software, we will take a few moments to help provide troubleshooting support, before moving on to the exercises.
+ 0:20 - ["Command Line Computing" Exercise](./exercises/command-line-computing/index.qmd):
  + Get comfortable navigating the filesystem using `cd` commands.
+ 0:35 - ["Hello Python" Exercise](./exercises/hello-python/index.qmd):
  + Write some code in a Python script, save it, and run it from the command line.
+ 0:50 - Break / Installation Support
+ 0:60 - ["Run the App (Tic Tac Toe)" Exercise](./exercises/run-the-app/index.qmd):
  + Download an existing Python app from GitHub, setup a virtual environment to satisfy the application's dependencies, and run the application from the command line.
+ 0:90 - Stop
